"""empty message

Revision ID: 29de2a009cc6
Revises: 7d8931730c98
Create Date: 2021-10-28 15:14:54.953952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29de2a009cc6'
down_revision = '7d8931730c98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('content', sa.Text(), nullable=True))
    op.add_column('question', sa.Column('create_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question', 'create_time')
    op.drop_column('question', 'content')
    # ### end Alembic commands ###
