"""empty message

Revision ID: 63da2aaa69d9
Revises: e49ad5a32f46
Create Date: 2021-10-28 21:57:05.243961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63da2aaa69d9'
down_revision = 'e49ad5a32f46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('user_id', sa.Integer(), server_default='1', nullable=True))
    op.create_foreign_key(None, 'question', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'question', type_='foreignkey')
    op.drop_column('question', 'user_id')
    # ### end Alembic commands ###
