"""empty message

Revision ID: 828fb19e975f
Revises: 
Create Date: 2021-10-27 11:11:05.856943

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '828fb19e975f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('question')
    # ### end Alembic commands ###
